name: Deploy Image Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Verzeichnisstruktur erstellen
            sudo mkdir -p /opt/image-service
            sudo chown www-data:www-data /opt/image-service
            sudo chmod 775 /opt/image-service
            sudo usermod -a -G www-data sebius

            # Zum Verzeichnis wechseln
            cd /opt/image-service

            # Git als www-data initialisieren
            if [ ! -d ".git" ]; then
              sudo -u www-data git init
              sudo -u www-data git config --global --add safe.directory /opt/image-service
              sudo -u www-data git remote add origin https://github.com/SaschaKohler/image-service.git
            fi

            # Code aktualisieren
            sudo -u www-data git fetch --all
            sudo -u www-data git reset --hard origin/main

            # Dependencies installieren und Service neustarten
            sudo -u www-data npm install --production
            sudo -u www-data pm2 restart image-service || sudo -u www-data pm2 start src/server.js --name image-service
