name: Deploy Image Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Als root ausführen
            sudo -i bash << 'EOF'

            # Verzeichnisse prüfen/erstellen
            mkdir -p /var/www/.pm2
            mkdir -p /var/www/pm2
            mkdir -p /opt/image-service

            # Berechtigungen setzen
            chown -R www-data:www-data /var/www/.pm2
            chown -R www-data:www-data /var/www/pm2
            chown -R www-data:www-data /opt/image-service
            chmod -R 775 /opt/image-service

            # Zum Verzeichnis wechseln
            cd /opt/image-service

            # Git als www-data initialisieren
            if [ ! -d ".git" ]; then
              sudo -u www-data git init
              sudo -u www-data git config --global --add safe.directory /opt/image-service
              sudo -u www-data git remote add origin https://github.com/SaschaKohler/image-service.git
            fi

            # Code aktualisieren
            sudo -u www-data git fetch --all
            sudo -u www-data git reset --hard origin/main

            # Dependencies installieren
            sudo -u www-data npm install --production

            # PM2 als www-data starten
            sudo -u www-data PM2_HOME=/var/www/.pm2 pm2 restart image-service || sudo -u www-data PM2_HOME=/var/www/.pm2 pm2 start src/server.js --name image-service

            # PM2 Startup sicherstellen
            env PATH=$PATH:/usr/bin PM2_HOME=/var/www/.pm2 pm2 startup systemd -u www-data --hp /var/www
            sudo -u www-data PM2_HOME=/var/www/.pm2 pm2 save

            EOF
