name: Deploy Image Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Verzeichnis vorbereiten wenn es nicht existiert
            if [ ! -d "/opt/image-service" ]; then
              sudo mkdir -p /opt/image-service
              sudo chown $USER:$USER /opt/image-service
            fi

            # Zum Verzeichnis wechseln
            cd /opt/image-service

            # Git initialisieren wenn noch nicht geschehen
            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/yourusername/image-service.git
            fi

            # Code aktualisieren
            git fetch --all
            git reset --hard origin/main

            # Dependencies installieren und Service neustarten
            npm install --production
            pm2 restart image-service || pm2 start src/server.js --name image-service
