# .github/workflows/initial-setup.yml
name: Initial Server Setup

on:
  workflow_dispatch:
    inputs:
      server_setup:
        description: 'Confirm initial server setup'
        required: true
        type: boolean

jobs:
  initial-setup:
    runs-on: ubuntu-latest
    if: github.event.inputs.server_setup == 'true'
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Initial Server Setup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Als root ausführen
            sudo -i bash << 'EOF'

            # Git global config für www-data
            sudo -u www-data git config --global init.defaultBranch main

            # Verzeichnisse vorbereiten
            mkdir -p /var/www/.pm2
            mkdir -p /var/www/.npm
            mkdir -p /opt/image-service

            # Berechtigungen setzen
            chown -R www-data:www-data /var/www/.pm2
            chown -R www-data:www-data /var/www/.npm
            chown -R www-data:www-data /opt/image-service

            # Repository Setup als www-data
            cd /opt/image-service
            rm -rf .git

            # Git Operationen als www-data
            sudo -u www-data bash << 'WWWDATA'
            cd /opt/image-service
            git init
            git config --global --add safe.directory /opt/image-service
            git remote add origin https://github.com/SaschaKohler/image-service.git
            git fetch origin
            git checkout -B main
            git reset --hard origin/main

            # NPM Installation mit erhöhtem Timeout
            npm config set script-timeout 600000
            npm install --production --no-fund --no-audit

            # Initialize database and run migrations
            echo "Initializing database and running migrations..."
            npm run db:migrate
            WWWDATA

            # PM2 Setup
            sudo -u www-data PM2_HOME=/var/www/.pm2 pm2 delete image-service || true
            sudo -u www-data PM2_HOME=/var/www/.pm2 pm2 start src/server.js --name image-service
            sudo -u www-data PM2_HOME=/var/www/.pm2 pm2 save

            # PM2 Startup
            env PATH=$PATH:/usr/bin PM2_HOME=/var/www/.pm2 pm2 startup systemd -u www-data --hp /var/www
            systemctl enable pm2-www-data
            systemctl start pm2-www-data

            # Setup-Markierung
            touch /opt/image-service/.initial-setup-complete
            EOF
